version: '3.8'

services:
  redirect:
    image: nginx:alpine
    container_name: stock_sim_redirect
    restart: always
    ports:
      - "3002:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
